services:
  web:
    build: .
    command: sh -c "uvicorn app.main:app --reload --host=0.0.0.0 --port=8000"
    ports:
      - 8000:8000
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant_data

configs:
  qdrant_config:
    content: |
            log_level: INFO